###### 用户权限相关的接口
POST http://10.119.9.180/auth/login/ HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

####
POST http://localhost:3100/auth/login/ HTTP/1.1
content-type: application/json

{
    "username": "user",
    "password": "sjtuwxbuser"
}

#########################
GET http://10.119.9.180/auth/me/ HTTP/1.1
#####

GET http://localhost:3100/auth/me/ HTTP/1.1

#####
GET http://10.119.9.180/auth/logout/ HTTP/1.1


###
GET http://localhost:3100/auth/logout/ HTTP/1.1

###### 
GET http://localhost:3100/api/process_task/ HTTP/1.1

#####
POST http://localhost:3100/api/comment_task/ HTTP/1.1
