POST http://10.119.4.98:8000/auth/login/ HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

#########################
GET http://10.119.4.98:8000/auth/me/ HTTP/1.1
